services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.8.0
    container_name: simplehr-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.8.0
    container_name: simplehr-kafka
    depends_on:
      - zookeeper
    ports:
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:9094
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  employee-db:
    image: postgres:16
    container_name: simplehr-employee-db
    environment:
      POSTGRES_DB: employee_db
      POSTGRES_USER: simplehr
      POSTGRES_PASSWORD: simplehr
    ports:
      - "5433:5432"
    volumes:
      - employee_db_data:/var/lib/postgresql/data

  leave-db:
    image: postgres:16
    container_name: simplehr-leave-db
    environment:
      POSTGRES_DB: leave_db
      POSTGRES_USER: simplehr
      POSTGRES_PASSWORD: simplehr
    ports:
      - "5434:5432"
    volumes:
      - leave_db_data:/var/lib/postgresql/data

  payroll-db:
    image: postgres:16
    container_name: simplehr-payroll-db
    environment:
      POSTGRES_DB: payroll_db
      POSTGRES_USER: simplehr
      POSTGRES_PASSWORD: simplehr
    ports:
      - "5435:5432"
    volumes:
      - payroll_db_data:/var/lib/postgresql/data

volumes:
  employee_db_data:
  leave_db_data:
  payroll_db_data:
